### ISSUE TITLE
Generate all images from several html file into one sprite sheet?

### ISSUE THREAD

**Issue by YingshanDeng** [2createStudio/postcss-sprites#54]
I have some problem which can not generate all images from several html file into one sprite sheet? Now I only can genrate sprite sheet from one file, my demo: https://github.com/YingshanDeng/polymer-generate-spritesheet

Can you give me some guide? Thank you! 😃

**Comment by vvasilev-** [comment]
To get single sprite from all `<style>` tags you need to pass them as single source. Probably you need something like [posthtml-collect-styles](https://github.com/canvaskisa/posthtml-collect-styles) to combine all styles into single source which can be processed by the plugin.

**Comment by YingshanDeng** [comment]
@vvasilev-  Thank you for your reply. In my project, using the Polymer, after build the release file, it  look like: 
```
<html>
<head></head>
<body>
    <dom-module>
        <template>
            <style>
                /*... */
            </style>
        </template>
    </dom-module>
    <dom-module>
        <template>
            <style>
                /*... */
            </style>
        </template>
    </dom-module>
    <dom-module>
        <template>
            <style>
                /*... */
            </style>
        </template>
    </dom-module>
    <!-- other dom-module  -->
</body>

</html>
```
And it can not collect all style tags together.

**Comment by vvasilev-** [comment]
I understand that you need separate `<style>` tags in the final output(I cloned your repo and ran the build process) but my idea was:

* Step 1: Combine styles into single temporary source.
* Step 2: Process through the spritesheet plugin.
* Step 3: Split the output to multiple `<style>` tags.

You need to do something like the steps above because the final result that you want isn't in scope of this project. :smile:

**Comment by YingshanDeng** [comment]
Ok, thank you very much! 😎
