### ISSUE TITLE
pretty log and option to disable log

### ISSUE THREAD

**Issue by zyy7259** [2createStudio/postcss-sprites#65]
Hi, great plugin. It helps me a lot generating sprites.

Here is a little request. I use this plugin with [postcss-cli](https://github.com/postcss/postcss-cli) Could you please format the log so it looks pretty and useful? Now it just prints a few lines of useless logs. And provide an option to disable log?

Thanks.

``` js
postcss-sprites: 0 spritesheet generated.
postcss-sprites: 0 spritesheet generated.
postcss-sprites: 0 spritesheet generated.
postcss-sprites: 0 spritesheet generated.
```

**Comment by vvasilev-** [comment]
@zyy7259 Can you give an example for logs that will be useful? :smile:

**Comment by zyy7259** [comment]
Maybe some key steps when generating the sprits, like initializing, checking (filtering), grouping, and etc. And maybe an option to disable logging.

**Comment by alexlafroscia** [comment]
I definitely second the ability to disable this. We run this plugin over dozens of stylesheets -- it's very noisy and not actually that useful.  Since `result.warn` is really meant to convey something actionable, if you're looking to provide general diagnostic information about how many spritesheets are being generated, maybe a tool like [`debug`](https://www.npmjs.com/package/debug) would be a way to do that and allow people to opt-in to the logging.

**Comment by jedmao** [comment]
I think this "warning" is the reason I have to look at this unsightly banner on my dev server:
![image](https://cloud.githubusercontent.com/assets/1058243/22680786/820a14d8-eccf-11e6-9bb6-5e56a2883dac.png)
