### ISSUE TITLE
How to supported retina @2x, @3x

### ISSUE THREAD

**Issue by NicholasNC** [2createStudio/postcss-sprites#86]
Hello, I want to realize function, like this:

In `/src/images/slice/` have two pic: `test.png` and `test@2x.png`

Css In
```
.icon-test {
    width: 32px;
    height: 32px;
    background-image: url(../slice/test.png);
}
```

Css Out
```
.icon-test {
    background-image: url(../sprite/style-index.png);
}

// Retina 2x supported
@media only screen and (-webkit-min-device-pixel-ratio: 2),
only screen and (min--moz-device-pixel-ratio: 2),
only screen and (-webkit-min-device-pixel-ratio: 2.5),
only screen and (min-resolution: 240dpi) {
.icon-test { 
    background-image:url("../sprite/style-index@2x.png");
    background-position: -36px -66px;
    background-size: 32px;
}
}
```

reference: [gulp-tmtsprite](https://github.com/weixin/gulp-tmtsprite)

**Comment by vvasilev-** [comment]
Hey @NicholasNC,

Sorry for the late response. Please set `retina` option to `true` and the plugin will start to generate the necessary CSS rules. 😄

**Comment by yangbin1994** [comment]
just set `retina`？

**Comment by vvasilev-** [comment]
@yangbin1994 Yes, just set the `retina` option.

**Comment by Lkroner** [comment]
Will this retina functionality support 3x images as well? Something like [this](https://github.com/glebmachine/postcss-easysprites#input-example). I don't see anything in your documentation about it.

**Comment by vvasilev-** [comment]
@Lkroner The `retina` option supports 3x images because of [these lines](https://github.com/2createStudio/postcss-sprites/blob/master/src/core.js#L452-L455). If something doesn't work as you expected, you can use `onUpdateRule` hook to implement the desired behavior. Here is an example - https://github.com/2createStudio/postcss-sprites/blob/master/examples/output-dimensions.md.
